---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: csi-blobfuse-proxy
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: csi-blobfuse-proxy
  template:
    metadata:
      labels:
        app: csi-blobfuse-proxy
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: NotIn
                    values:
                      - virtual-kubelet
      containers:
      - command:
          - nsenter
          - '--target'
          - '1'
          - '--mount'
          - '--uts'
          - '--ipc'
          - '--net'
          - '--pid'
          - '--'
          - sh
          - '-c'
          - |
            set -xe
            wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
            dpkg -i packages-microsoft-prod.deb
            apt-get update && apt-get install -y blobfuse
            # download blobfuse-proxy .deb package
            wget https://github.com/kubernetes-sigs/blob-csi-driver/raw/master/deploy/blobfuse-proxy/v0.1.0/blobfuse-proxy-v0.1.0.deb -O /tmp/blobfuse-proxy-v0.1.0.deb
            dpkg -i /tmp/blobfuse-proxy-v0.1.0.deb
            mkdir -p /var/lib/kubelet/plugins/blob.csi.azure.com
            echo "Enabling blobfuse proxy systemctl service"
            systemctl daemon-reload
            systemctl enable blobfuse-proxy
            systemctl start blobfuse-proxy
            echo "removing the file: /tmp/blobfuse-proxy-v0.1.0.deb"
            rm /tmp/blobfuse-proxy-v0.1.0.deb
            echo "waiting for blobfuse-proxy service to start"
            sleep 3s
            # tail blobfuse proxy logs
            journalctl -u blobfuse-proxy -f
        image: mcr.microsoft.com/oss/nginx/nginx:1.17.3-alpine
        imagePullPolicy: IfNotPresent
        name: sysctl-install-blobfuse-proxy
        resources:
          requests:
            cpu: 10m
        securityContext:
          privileged: true
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      restartPolicy: Always
      tolerations:
        - operator: Exists
