language: go
go_import_path: github.com/csi-driver/blobfuse-csi-driver
dist: bionic

env:
  global:
    - GO111MODULE=off

go:
  - "1.12.1"

jobs:
  include:
    - stage: test
      name: "build test"
      install:
        - GO111MODULE=off go get github.com/mattn/goveralls
        - go get github.com/golang/dep/cmd/dep
      script:
        - hack/verify-all.sh
        - make blobfuse
        - make blobfuse-container
        - make blobfuse-windows
        - go test -covermode=count -coverprofile=profile.cov ./pkg/...
    - stage: test
      name: "sanity test"
      script: make sanity-test
      after_failure: TRAVIS_TEST_RESULT=0
    - stage: test
      name: "integration test"
      install:
        - GO111MODULE=off go get github.com/rexray/gocsi/csc
      script:
        - make blobfuse
        - make integration-test
