---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-blobfuse
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: blob
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: deployment-blob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      name: deployment-blob
    spec:
      containers:
        - name: deployment-blob
          image: nginx
          command:
            - "/bin/sh"
            - "-c"
            - while true; do echo $(date) >> /mnt/blob/outfile; sleep 1; done
          volumeMounts:
            - name: blobfuse
              mountPath: "/mnt/blob"
              readOnly: false
      volumes:
        - name: blobfuse
          persistentVolumeClaim:
            claimName: pvc-blobfuse
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
