---
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: blob.csi.azure.com
  name: pv-blob
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: blob-fuse
  mountOptions:
    - -o allow_other
    - --file-cache-timeout-in-seconds=120
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    # make sure volumeid is unique for every storage blob container in the cluster
    # the # character is reserved for internal use
    volumeHandle: account-name_container-name
    volumeAttributes:
      resourceGroup: EXISTING_RESOURCE_GROUP_NAME
      storageAccount: EXISTING_STORAGE_ACCOUNT_NAME
      containerName: EXISTING_CONTAINER_NAME
      # refer to https://github.com/Azure/azure-storage-fuse#environment-variables
      AzureStorageAuthType: key  # key, sas, msi, spn
      AzureStorageIdentityClientID:
      AzureStorageIdentityObjectID:
      AzureStorageIdentityResourceID:
      MSIEndpoint:
      AzureStorageSPNClientID:
      AzureStorageSPNTenantID:
      AzureStorageAADEndpoint:
    nodeStageSecretRef:  # secret should be stored here
      name: azure-secret
      namespace: default
