apiVersion: v1
entries:
  blob-csi-driver:
  - apiVersion: v1
    appVersion: v1.20.0
    created: "2023-02-23T13:03:48.731999637Z"
    description: Azure Blob Storage CSI driver
    digest: 5c42426b0cd6b80ecfd6a3fb5c1d84c45b38662956e0106ab99505d1cef32517
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/latest/blob-csi-driver-v1.20.0.tgz
    version: v1.20.0
  - apiVersion: v1
    appVersion: v1.20.0
    created: "2023-02-23T13:03:48.773072325Z"
    description: Azure Blob Storage CSI driver
    digest: df29e60561b660c952441d002291be488856a512c325e2b534c8ff0eab9692b7
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.20.0/blob-csi-driver-v1.20.0.tgz
    version: v1.20.0
  - apiVersion: v1
    appVersion: v1.19.0
    created: "2023-02-23T13:03:48.769051058Z"
    description: Azure Blob Storage CSI driver
    digest: 1e2a42d12b750ad3bb7e287bb0524a0f896568384779509473541693b4440939
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.19.0/blob-csi-driver-v1.19.0.tgz
    version: v1.19.0
  - apiVersion: v1
    appVersion: v1.18.0
    created: "2023-02-23T13:03:48.768102707Z"
    description: Azure Blob Storage CSI driver
    digest: 3eac15488da5be7d1e78431929f7cda35bceb1af3fe107ffbd84606e047c9204
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.18.0/blob-csi-driver-v1.18.0.tgz
    version: v1.18.0
  - apiVersion: v1
    appVersion: v1.17.0
    created: "2023-02-23T13:03:48.767185138Z"
    description: Azure Blob Storage CSI driver
    digest: 22cfa17fc5e8d771ff8edd26729266a9a8ee55c0e150df85ef15698f7fe985e9
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.17.0/blob-csi-driver-v1.17.0.tgz
    version: v1.17.0
  - apiVersion: v1
    appVersion: v1.16.0
    created: "2023-02-23T13:03:48.763411498Z"
    description: Azure Blob Storage CSI driver
    digest: bf6249c0e3e3d3d009d4c79ceb7fda9a56c0565b969de753628792ea3ea5ece8
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.16.0/blob-csi-driver-v1.16.0.tgz
    version: v1.16.0
  - apiVersion: v1
    appVersion: v1.15.0
    created: "2023-02-23T13:03:48.761151158Z"
    description: Azure Blob Storage CSI driver
    digest: 8daa35cd4957695cb64b45da05a15b4020df5545a8ac44c4668dad4bba82c8a9
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.15.0/blob-csi-driver-v1.15.0.tgz
    version: v1.15.0
  - apiVersion: v1
    appVersion: v1.14.0
    created: "2023-02-23T13:03:48.760049305Z"
    description: Azure Blob Storage CSI driver
    digest: 442bc579b231aab626b9e474e2c0ed3f101d47d61c99aa9a7f863af7ce268d9d
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.14.0/blob-csi-driver-v1.14.0.tgz
    version: v1.14.0
  - apiVersion: v1
    appVersion: v1.13.0
    created: "2023-02-23T13:03:48.756464474Z"
    description: Azure Blob Storage CSI driver
    digest: b577b0b771138109aa90eb09d56fc07273ca0b584a263ee8f789e35796279f31
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.13.0/blob-csi-driver-v1.13.0.tgz
    version: v1.13.0
  - apiVersion: v1
    appVersion: v1.12.0
    created: "2023-02-23T13:03:48.755513736Z"
    description: Azure Blob Storage CSI driver
    digest: 124e87af2581b374b89a39940698620c23d3eae6dcee518d302461ffea93e9a8
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.12.0/blob-csi-driver-v1.12.0.tgz
    version: v1.12.0
  - apiVersion: v1
    appVersion: v1.11.0
    created: "2023-02-23T13:03:48.75353005Z"
    description: Azure Blob Storage CSI driver
    digest: 07c4d76017491b3d0bdd70de90e814096938bf7916da0c149c3805294bd57560
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.11.0/blob-csi-driver-v1.11.0.tgz
    version: v1.11.0
  - apiVersion: v1
    appVersion: v1.10.0
    created: "2023-02-23T13:03:48.752626106Z"
    description: Azure Blob Storage CSI driver
    digest: 79716efa958385adf57eb3570843e1b4512d8c801e8e070625e94264f3e917a9
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.10.0/blob-csi-driver-v1.10.0.tgz
    version: v1.10.0
  - apiVersion: v1
    appVersion: v1.9.0
    created: "2023-02-23T13:03:48.793250767Z"
    description: Azure Blob Storage CSI driver
    digest: fca0b9215d3277346f68c643fb3ead75158971f0d1945ab01ec559196f3cf842
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.9.0/blob-csi-driver-v1.9.0.tgz
    version: v1.9.0
  - apiVersion: v1
    appVersion: v1.8.0
    created: "2023-02-23T13:03:48.78970799Z"
    description: Azure Blob Storage CSI driver
    digest: 3b78e2ab4f33577c54d4f57276c824717d2ad2aa3741210e938fcaf927bc751f
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.8.0/blob-csi-driver-v1.8.0.tgz
    version: v1.8.0
  - apiVersion: v1
    appVersion: v1.7.0
    created: "2023-02-23T13:03:48.788643099Z"
    description: Azure Blob Storage CSI driver
    digest: 28da5b55c3d2689d6da85eb7da344385e9cb99bdb2af18c24fea93670abfe7ea
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.7.0/blob-csi-driver-v1.7.0.tgz
    version: v1.7.0
  - apiVersion: v1
    appVersion: v1.6.0
    created: "2023-02-23T13:03:48.784848737Z"
    description: Azure Blob Storage CSI driver
    digest: 6f24f2e6623f6f8862e47d4fbdf13b5f351ceec6bb9a4591ef7fc2fca9fc1eef
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.6.0/blob-csi-driver-v1.6.0.tgz
    version: v1.6.0
  - apiVersion: v1
    appVersion: v1.5.0
    created: "2023-02-23T13:03:48.783710806Z"
    description: Azure Blob Storage CSI driver
    digest: 95d14c9b70b319760d388ea47727c8c97e9287867a8852aeb67b7175b52fe8f5
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.5.0/blob-csi-driver-v1.5.0.tgz
    version: v1.5.0
  - apiVersion: v1
    appVersion: v1.4.1
    created: "2023-02-23T13:03:48.782832507Z"
    description: Azure Blob Storage CSI driver
    digest: 5fcf69c449f065fa1d5722e5a7fed8a28000efa790907e9ff4b552c5fbd16d22
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.4.1/blob-csi-driver-v1.4.1.tgz
    version: v1.4.1
  - apiVersion: v1
    appVersion: v1.4.0
    created: "2023-02-23T13:03:48.780895837Z"
    description: Azure Blob Storage CSI driver
    digest: b466543344a6411f6130ba87b093955d39ab8614c6b4ed8505a0a0c96073cb33
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.4.0/blob-csi-driver-v1.4.0.tgz
    version: v1.4.0
  - apiVersion: v1
    appVersion: v1.3.0
    created: "2023-02-23T13:03:48.777133084Z"
    description: Azure Blob Storage CSI driver
    digest: 58d02cb70a3a966b349d62e880b7149fb06ac009474e35e580784fd3c98a5b07
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.3.0/blob-csi-driver-v1.3.0.tgz
    version: v1.3.0
  - apiVersion: v1
    appVersion: v1.2.0
    created: "2023-02-23T13:03:48.772301017Z"
    description: Azure Blob Storage CSI driver
    digest: 27fb89f20b5fddc7329e6d7c2374857b22c1d61592e397a53f47121eea68c344
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.2.0/blob-csi-driver-v1.2.0.tgz
    version: v1.2.0
  - apiVersion: v1
    appVersion: v1.1.0
    created: "2023-02-23T13:03:48.751519773Z"
    description: Azure Blob Storage CSI driver
    digest: a251a55243de207c69ef53f72abee45e93b72fa4fc43dc204b7f1cdfd459acdb
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.1.0/blob-csi-driver-v1.1.0.tgz
    version: v1.1.0
  - apiVersion: v1
    appVersion: v1.0.0
    created: "2023-02-23T13:03:48.742776462Z"
    description: Azure Blob Storage CSI driver
    digest: e83f037a165eafc83a978bd7e6bf6221b052ac34363aecb12e6a73607dc58b89
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/v1.0.0/blob-csi-driver-v1.0.0.tgz
    version: v1.0.0
  - apiVersion: v1
    appVersion: latest
    created: "2023-02-23T13:03:48.731394392Z"
    description: Azure Blob Storage CSI driver
    digest: f8fb3820c550867e0e2468bb593a3e3d45e6b4fb283b66100d5f6bab0c0d8a47
    name: blob-csi-driver
    urls:
    - https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/master/charts/latest/blob-csi-driver-v0.0.0.tgz
    version: v0.0.0
generated: "2023-02-23T13:03:48.730630059Z"
