name: Linux Tests
on:
    pull_request: {}
    push: {}

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ^1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Run build test
      run: |
        export PATH=$PATH:$HOME/.local/bin
        make

    - name: Make container test
      run: |
        export PATH=$PATH:$HOME/.local/bin
        make container

    - name: Make blobfuse-proxy test
      run: |
        export PATH=$PATH:$HOME/.local/bin
        make blobfuse-proxy

    - name: Run unit test
      run: |
        export PATH=$PATH:$HOME/.local/bin
        wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update
        sudo apt-get install blobfuse
        go test -race -covermode=atomic -coverprofile=profile.cov ./pkg/...

    - name: Install goveralls
      run: go install github.com/mattn/goveralls@latest

    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: goveralls -coverprofile=profile.cov -service=github -ignore=./pkg/blobfuse-proxy/pb
